import "./globals.css";
import { AuthContextProvider } from "./context/authContext.jsx";
import { ToastContainer, Zoom } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { Poppins, Inter } from "next/font/google";
import { PostContextProvider } from "./context/postContext";
import { Analytics } from "@vercel/analytics/next";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "600", "700"], // choose weights you need
  variable: "--font-poppins",
});

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-inter",
});

export const metadata = {
  title: "Campusforum App",
  description: "Generated by Campusforum app",
};

export default async function RootLayout({ children }) {
  return (
    <html lang="en" className={`${poppins.variable} ${inter.variable}`}>
      <body className="min-h-full flex flex-col">
        <AuthContextProvider>
          <PostContextProvider>
            <ToastContainer
              position="top-right"
              autoClose={1500}
              transition={Zoom}
              toastClassName="custom-toast"
            />
            {children}
            <Analytics />
          </PostContextProvider>
        </AuthContextProvider>
      </body>
    </html>
  );
}
