import "./globals.css";
import { AuthContextProvider } from "./context/authContext.jsx";
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import { Poppins, Inter } from "next/font/google";
import { PostContextProvider } from "./context/postContext";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "600", "700"], // choose weights you need
  variable: "--font-poppins",
});

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-inter",
});

export const metadata = {
  title: "CampusHub App",
  description: "Generated by CampusHub app",
};

export default async function RootLayout({ children }) {
  
  return (
    <html
      lang="en"
      className={`${poppins.variable} ${inter.variable}`}
    >
      <body className="min-h-full flex flex-col">
        <AuthContextProvider>
          <PostContextProvider>
            <ToastContainer position="top-right" autoClose={3000} />
            {children}
          </PostContextProvider>
        </AuthContextProvider>
      </body>
    </html>
  );
}
